<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseCompiledBindingsByDefault>true</UseCompiledBindingsByDefault>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <UsedAvaloniaProducts></UsedAvaloniaProducts>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <None Update="Assets\Fonts\NetflixSans-Bold.otf" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.*" />
    <PackageReference Include="Avalonia.Desktop" Version="12.*" />
    <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.*" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.*" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.*" />
    <PackageReference Include="LibVLCSharp" Version="3.*" />
    <PackageReference Include="LibVLCSharp.Avalonia" Version="3.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.*" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.*" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.*" />
  </ItemGroup>
</Project>
